entry: loop
main: "./web_server_accel.c"
hook: sk_skb
framework: poll
sources: [
  "libs/picohttpparser.c",
]
out_bpf: "./build/web_server_accel.bpf.c"
out_user: "./build/web_server_accel.user.c"
cflags: ""
